[package]
name = "dbmod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Emilk
eframe = { version = "0.19.0" }

# JSON
serde_json = "1.0"

# PostgreSQL
postgres = "0.19.4"